name: Pipeline básico

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Ejecutar comando
      run: echo "Hola desde GitHub Actions"
